modLoader="javafml"
loaderVersion="[47,)"
license="GPLv3"

[[mods]]
modId="notchnet"
version="${version}"
displayName="NotchNet"
authors="ravistarr"
description="AI-powered answers in Minecraft!"

[[dependencies.notchnet]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.notchnet]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
