name: Release Mod
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'aaravchour'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build Mod
        run: ./gradlew build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish to Modrinth & CurseForge
        uses: HypherionSA/mod-publisher-action@v1
        with:
          # Required tokens
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          # Project IDs (You must create these on the sites first)
          modrinth-id: 'Pv4jih5B'
          curseforge-id: '1410384'
          
          # Metadata
          version: ${{ github.ref_name }}
          changelog: 'Automatic release from tag ${{ github.ref_name }}'
          version-type: 'release'
          
          # Files to upload
          file: 'build/libs/notchnet-${{ github.ref_name }}.jar'
          loaders: 'fabric'
          game-versions: '1.21.1,1.21.11'
