name: Release Mod
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'aaravchour'
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Version from gradle.properties
        id: get_version
        run: |
          VERSION=$(grep "mod_version" gradle.properties | cut -d'=' -f2 | xargs)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      
      - name: Build Mod
        run: ./gradlew build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish to Platforms
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Required tokens
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Project IDs
          modrinth-id: 'Pv4jih5B'
          curseforge-id: '1410384'
          
          # Metadata
          version: ${{ steps.get_version.outputs.version }}
          name: 'NotchNet ${{ steps.get_version.outputs.version }}'
          changelog: 'Automatic release of version ${{ steps.get_version.outputs.version }}'
          version-type: 'release'
          
          # Files to upload
          files: 'build/libs/notchnet-${{ steps.get_version.outputs.version }}.jar'
          loaders: 'fabric'
          game-versions: |
            1.21.1
            1.21
